const mealIds=['breakfast','lunch','snack','dinner','eveningSnack'];
const fields=[...mealIds,'weight','burned'];
const $=id=>document.getElementById(id);
const storeKey='steady-weight-tracker-v1';
let data={days:{},photos:[]};
try{const saved=JSON.parse(localStorage.getItem(storeKey)||'{}');data={days:saved.days&&typeof saved.days==='object'?saved.days:{},photos:Array.isArray(saved.photos)?saved.photos:[]}}catch(error){console.warn('Saved tracker data could not be read.',error)}
let chartType='weight';
const isoToday=()=>new Date().toISOString().slice(0,10);
const shortDate=date=>new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric'}).format(new Date(date+'T12:00:00'));
const longDate=date=>new Intl.DateTimeFormat(undefined,{weekday:'short',year:'numeric',month:'short',day:'numeric'}).format(new Date(date+'T12:00:00'));
const foodFor=day=>mealIds.reduce((sum,id)=>sum+(Number(day[id])||0),0);
function save(){localStorage.setItem(storeKey,JSON.stringify(data))}
function getFood(){return mealIds.reduce((sum,id)=>sum+(Number($(id).value)||0),0)}
function updateSummary(){const food=getFood(),burned=Number($('burned').value)||0,deficit=burned-food;$('foodTotal').textContent=food.toLocaleString();$('balance').textContent=Math.abs(deficit).toLocaleString();$('balanceNote').textContent=deficit>=0?'kcal deficit':'kcal over burned';$('fatChange').textContent=(deficit/7700).toFixed(2)}
function loadDay(){const day=data.days[$('logDate').value]||{};fields.forEach(id=>$(id).value=day[id]??'');updateSummary()}
function saveDay(){const date=$('logDate').value;if(!date)return;data.days[date]=Object.fromEntries(fields.map(id=>[id,$(id).value]));save();renderChart();renderHistory();$('saveDay').textContent='Saved ✓';setTimeout(()=>{$('saveDay').innerHTML='Save daily check-in <span>→</span>'},1400)}
function entries(){return Object.entries(data.days).sort(([a],[b])=>a.localeCompare(b)).map(([date,d])=>({date,weight:Number(d.weight),food:foodFor(d),burned:Number(d.burned)||0,deficit:(Number(d.burned)||0)-foodFor(d)}))}
function renderHistory(){const all=entries().reverse(),list=$('historyList');$('historyCount').textContent=all.length?`${all.length} saved ${all.length===1?'day':'days'}`:'No saved days';list.innerHTML='';if(!all.length){list.innerHTML='<div class="history-empty">Your saved daily check-ins will appear here.</div>';return}all.forEach(entry=>{const row=document.createElement('div');row.className='history-row';const detail=[`${entry.food.toLocaleString()} kcal eaten`,entry.burned?`${entry.burned.toLocaleString()} kcal burned`:null,entry.weight?`${entry.weight.toFixed(1)} kg`:null].filter(Boolean).join(' · ');row.innerHTML=`<div><strong>${longDate(entry.date)}</strong><span>${detail||'No values yet'}</span></div><button type="button">Edit</button>`;row.querySelector('button').onclick=()=>{$('logDate').value=entry.date;loadDay();window.scrollTo({top:0,behavior:'smooth'})};list.append(row)})}
function renderChart(){const all=entries(),valid=chartType==='weight'?all.filter(x=>x.weight>0):all,canvas=$('progressChart'),empty=$('emptyChart');$('entriesCount').textContent=all.length?`${all.length} saved ${all.length===1?'day':'days'}`:'No entries yet';empty.hidden=valid.length>0;if(!valid.length){$('chartCaption').textContent='';return}const dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);const vals=chartType==='weight'?valid.map(x=>x.weight):valid.map((x,i)=>valid.slice(0,i+1).reduce((s,y)=>s+y.deficit,0)/7700);let min=Math.min(...vals),max=Math.max(...vals);if(min===max){min-=1;max+=1}const pad={l:42,r:12,t:20,b:34},px=i=>pad.l+(w-pad.l-pad.r)*(valid.length===1?.5:i/(valid.length-1)),py=v=>pad.t+(max-v)/(max-min)*(h-pad.t-pad.b);c.strokeStyle='#e5ddd0';c.lineWidth=1;for(let i=0;i<4;i++){const y=pad.t+i*(h-pad.t-pad.b)/3;c.beginPath();c.moveTo(pad.l,y);c.lineTo(w-pad.r,y);c.stroke();c.fillStyle='#738078';c.font='10px DM Sans';c.fillText((max-(max-min)*i/3).toFixed(1),2,y+3)}c.beginPath();valid.forEach((v,i)=>i?c.lineTo(px(i),py(vals[i])):c.moveTo(px(i),py(vals[i])));c.strokeStyle='#ea7751';c.lineWidth=3;c.lineJoin='round';c.stroke();valid.forEach((v,i)=>{c.beginPath();c.arc(px(i),py(vals[i]),4,0,Math.PI*2);c.fillStyle='#fffdf9';c.fill();c.strokeStyle='#ea7751';c.lineWidth=2;c.stroke();if(i===0||i===valid.length-1){c.fillStyle='#738078';c.font='10px DM Sans';c.textAlign=i?'right':'left';c.fillText(shortDate(v.date),px(i),h-8)}});c.textAlign='start';$('chartCaption').textContent=chartType==='weight'?`Latest weight: ${valid.at(-1).weight.toFixed(1)} kg`:`Estimated cumulative fat change: ${vals.at(-1).toFixed(2)} kg`}
function renderPhotos(){const grid=$('photoGrid'),tpl=$('photoTemplate');grid.innerHTML='';data.photos.sort((a,b)=>b.date.localeCompare(a.date)).forEach(photo=>{const node=tpl.content.cloneNode(true);node.querySelector('img').src=photo.src;node.querySelector('img').alt=`Progress photo from ${shortDate(photo.date)}`;node.querySelector('span').textContent=shortDate(photo.date);node.querySelector('button').onclick=()=>{data.photos=data.photos.filter(p=>p.id!==photo.id);save();renderPhotos()};grid.append(node)})}
function exportBackup(){const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),...data})],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`steady-backup-${isoToday()}.json`;link.click();URL.revokeObjectURL(url)}
function importBackup(file){const reader=new FileReader();reader.onload=()=>{try{const backup=JSON.parse(reader.result);if(!backup.days||!Array.isArray(backup.photos))throw new Error('Invalid backup');if(!confirm('Restore this backup? It will replace the current saved tracker data on this device.'))return;data={days:backup.days,photos:backup.photos};save();loadDay();renderChart();renderHistory();renderPhotos();alert('Backup restored.')}catch(error){alert('This file is not a valid tracker backup.')}};reader.readAsText(file)}
$('logDate').value=isoToday();$('todayLabel').textContent=new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric'}).format(new Date());fields.forEach(id=>$(id).addEventListener('input',updateSummary));$('logDate').addEventListener('change',loadDay);$('saveDay').addEventListener('click',saveDay);document.querySelectorAll('[data-chart]').forEach(button=>button.onclick=()=>{chartType=button.dataset.chart;document.querySelectorAll('[data-chart]').forEach(item=>item.classList.toggle('active',item===button));renderChart()});$('photoInput').addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{data.photos.push({id:crypto.randomUUID(),date:$('logDate').value,src:reader.result});save();renderPhotos()};reader.readAsDataURL(file);event.target.value=''});$('exportData').addEventListener('click',exportBackup);$('importData').addEventListener('change',event=>{const file=event.target.files[0];if(file)importBackup(file);event.target.value=''});window.addEventListener('resize',renderChart);loadDay();renderChart();renderHistory();renderPhotos();
