const mealIds=['breakfast','lunch','snack','dinner','eveningSnack'];
const fields=[...mealIds,'weight','burned'];
const $=id=>document.getElementById(id);
const storeKey='steady-weight-tracker-v1';
let data=JSON.parse(localStorage.getItem(storeKey)||'{"days":{},"photos":[]}');
let chartType='weight';
const isoToday=()=>new Date().toISOString().slice(0,10);
const shortDate=date=>new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric'}).format(new Date(date+'T12:00:00'));
function save(){localStorage.setItem(storeKey,JSON.stringify(data))}
function getFood(){return mealIds.reduce((sum,id)=>sum+(Number($(id).value)||0),0)}
function updateSummary(){const food=getFood(), burned=Number($('burned').value)||0, deficit=burned-food; $('foodTotal').textContent=food.toLocaleString();$('balance').textContent=Math.abs(deficit).toLocaleString();$('balanceNote').textContent=deficit>=0?'kcal deficit':'kcal over burned';$('fatChange').textContent=(deficit/7700).toFixed(2)}
function loadDay(){const day=data.days[$('logDate').value]||{};fields.forEach(id=>$(id).value=day[id]??'');updateSummary()}
function saveDay(){const date=$('logDate').value;if(!date)return;data.days[date]=Object.fromEntries(fields.map(id=>[id,$(id).value]));save();renderChart();$('saveDay').textContent='Saved ✓';setTimeout(()=>{$('saveDay').innerHTML='Save daily check-in <span>→</span>'},1400)}
function entries(){return Object.entries(data.days).sort(([a],[b])=>a.localeCompare(b)).map(([date,d])=>({date,weight:Number(d.weight),deficit:(Number(d.burned)||0)-mealIds.reduce((s,id)=>s+(Number(d[id])||0),0)}))}
function renderChart(){const all=entries(), valid=chartType==='weight'?all.filter(x=>x.weight>0):all;const canvas=$('progressChart'), empty=$('emptyChart');$('entriesCount').textContent=all.length?`${all.length} saved ${all.length===1?'day':'days'}`:'No entries yet';empty.hidden=valid.length>0;if(!valid.length){$('chartCaption').textContent='';return}const dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);let vals=chartType==='weight'?valid.map(x=>x.weight):valid.map((x,i)=>valid.slice(0,i+1).reduce((s,y)=>s+y.deficit,0)/7700);let min=Math.min(...vals),max=Math.max(...vals);if(min===max){min-=1;max+=1}const pad={l:42,r:12,t:20,b:34}, px=i=>pad.l+(w-pad.l-pad.r)*(valid.length===1?.5:i/(valid.length-1)),py=v=>pad.t+(max-v)/(max-min)*(h-pad.t-pad.b);c.strokeStyle='#e5ddd0';c.lineWidth=1;for(let i=0;i<4;i++){let y=pad.t+i*(h-pad.t-pad.b)/3;c.beginPath();c.moveTo(pad.l,y);c.lineTo(w-pad.r,y);c.stroke();c.fillStyle='#738078';c.font='10px DM Sans';c.fillText((max-(max-min)*i/3).toFixed(1),2,y+3)}c.beginPath();valid.forEach((v,i)=>i?c.lineTo(px(i),py(vals[i])):c.moveTo(px(i),py(vals[i])));c.strokeStyle='#ea7751';c.lineWidth=3;c.lineJoin='round';c.stroke();valid.forEach((v,i)=>{c.beginPath();c.arc(px(i),py(vals[i]),4,0,Math.PI*2);c.fillStyle='#fffdf9';c.fill();c.strokeStyle='#ea7751';c.lineWidth=2;c.stroke();if(i===0||i===valid.length-1){c.fillStyle='#738078';c.font='10px DM Sans';c.textAlign=i?'right':'left';c.fillText(shortDate(v.date),px(i),h-8)}});c.textAlign='start';$('chartCaption').textContent=chartType==='weight'?`Latest weight: ${valid.at(-1).weight.toFixed(1)} kg`:`Estimated cumulative fat change: ${vals.at(-1).toFixed(2)} kg`}
function renderPhotos(){const grid=$('photoGrid'),tpl=$('photoTemplate');grid.innerHTML='';data.photos.sort((a,b)=>b.date.localeCompare(a.date)).forEach(photo=>{const node=tpl.content.cloneNode(true);node.querySelector('img').src=photo.src;node.querySelector('img').alt=`Progress photo from ${shortDate(photo.date)}`;node.querySelector('span').textContent=shortDate(photo.date);node.querySelector('button').onclick=()=>{data.photos=data.photos.filter(p=>p.id!==photo.id);save();renderPhotos()};grid.append(node)})}
$('logDate').value=isoToday();$('todayLabel').textContent=new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric'}).format(new Date());fields.forEach(id=>$(id).addEventListener('input',updateSummary));$('logDate').addEventListener('change',loadDay);$('saveDay').addEventListener('click',saveDay);document.querySelectorAll('[data-chart]').forEach(b=>b.onclick=()=>{chartType=b.dataset.chart;document.querySelectorAll('[data-chart]').forEach(x=>x.classList.toggle('active',x===b));renderChart()});$('photoInput').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{data.photos.push({id:crypto.randomUUID(),date:$('logDate').value,src:reader.result});save();renderPhotos()};reader.readAsDataURL(file);e.target.value=''});window.addEventListener('resize',renderChart);loadDay();renderChart();renderPhotos();
