const defaultFoods={bread:{name:'Bread',kcal:250},eggs:{name:'Eggs',kcal:143},rice:{name:'Cooked rice',kcal:130},potatoes:{name:'Potatoes',kcal:75},spaghetti:{name:'Cooked spaghetti',kcal:158},macaroni:{name:'Cooked macaroni',kcal:131},chicken:{name:'Chicken (raw)',kcal:85},quark:{name:'Quark',kcal:67},blueberries:{name:'Blueberries',kcal:57},ham:{name:'Ham',kcal:110},milk:{name:'Milk',kcal:46},muesli:{name:'Muesli',kcal:370}};
const mealNames={breakfast:'Breakfast',lunch:'Lunch',snack:'Snack',dinner:'Dinner',eveningSnack:'Evening snack'};
const suggested={breakfast:'bread',lunch:'rice',snack:'quark',dinner:'potatoes',eveningSnack:'bread'};
const foods=()=>({...Object.fromEntries(Object.entries(defaultFoods).map(([id,food])=>[id,{...food,...(data.foods[id]||{})}])),...Object.fromEntries(Object.entries(data.foods).filter(([id])=>!defaultFoods[id]))});
let activeMealItems={};
const loadMealItems=()=>{activeMealItems=data.days[$('logDate').value]?.mealItems||{}};
const itemsFor=meal=>activeMealItems[meal]||[];
function updateMeal(meal){const all=foods(),total=itemsFor(meal).reduce((sum,item)=>sum+(Number(item.grams)||0)*(Number(all[item.foodId]?.kcal)||0)/100,0);if(itemsFor(meal).length){$(meal).value=Math.round(total);updateSummary()}}
function renderBuilders(){const host=$('mealBuilders'),all=foods();host.innerHTML='';mealIds.forEach(meal=>{const card=document.createElement('div');card.className='meal-builder';card.innerHTML=`<h3>${mealNames[meal]}</h3>`;itemsFor(meal).forEach((item,index)=>{const row=document.createElement('div');row.className='food-row';const select=document.createElement('select');Object.entries(all).forEach(([id,food])=>select.add(new Option(food.name,id,id===item.foodId,id===item.foodId)));const grams=document.createElement('input');grams.type='number';grams.inputMode='numeric';grams.min='0';grams.placeholder='g';grams.value=item.grams||'';const remove=document.createElement('button');remove.type='button';remove.textContent='×';const sync=()=>{item.foodId=select.value;item.grams=grams.value;updateMeal(meal);save()};select.onchange=sync;grams.oninput=sync;remove.onclick=()=>{activeMealItems[meal].splice(index,1);updateMeal(meal);save();renderBuilders()};row.append(select,grams,remove);card.append(row)});const kcal=document.createElement('p');kcal.className='food-kcal';kcal.textContent=itemsFor(meal).length?`${$(meal).value||0} kcal calculated from foods`:'Add foods to calculate this meal';const add=document.createElement('button');add.type='button';add.className='add-item';add.textContent='+ Add food';add.onclick=()=>{activeMealItems[meal]??=[];activeMealItems[meal].push({foodId:suggested[meal],grams:100});updateMeal(meal);save();renderBuilders()};card.append(kcal,add);host.append(card)})}
function renderFoodLibrary(){const host=$('foodLibrary'),all=foods();host.innerHTML='';Object.entries(all).forEach(([id,food])=>{const card=document.createElement('div');card.className='food-editor';const name=document.createElement('input');name.value=food.name;const kcal=document.createElement('input');kcal.type='number';kcal.inputMode='decimal';kcal.min='0';kcal.value=food.kcal;const saveFood=()=>{data.foods[id]={name:name.value||food.name,kcal:Number(kcal.value)||0};save();renderBuilders()};name.onchange=saveFood;kcal.onchange=saveFood;card.innerHTML='<label>Food name</label>';card.append(name);const label=document.createElement('label');label.textContent='kcal / 100 g';card.append(label,kcal);const note=document.createElement('small');note.textContent=data.foods[id]?'Your personal value':'Default value';card.append(note);host.append(card)})}
$('logDate').addEventListener('change',()=>{loadMealItems();renderBuilders()});$('saveDay').addEventListener('click',()=>{const day=data.days[$('logDate').value]??={};day.mealItems=activeMealItems;save();renderHistory()});$('addFood').addEventListener('click',()=>{const name=prompt('Food name');if(!name)return;const kcal=Number(prompt('Calories per 100 g','100'));if(!Number.isFinite(kcal))return;data.foods[`custom-${Date.now()}`]={name,kcal};save();renderFoodLibrary();renderBuilders()});loadMealItems();renderFoodLibrary();renderBuilders();
